name: Validation

env:
  GH_TOKEN: ${{ github.token }}

# Trigger when
on:
  # Push occurs in the main branch
  push:
    branches:
      - main

  # Pull request occurs in the main branch
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ok-nick/setup-aftman@v0.3.0
        with:
          version: v1.0.0 # name of git tag
          path: some_directory/my_project # path to project directory containing `aftman.toml`
          token: ${{ github.token }} # GitHub token to bypass rate limit
      
      - name: Lint
        run: selene src spec
  
  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          version: 3.0.0
          args: --check .
          token: ${{ github.token }}
