name: Validation

env:
  GH_TOKEN: ${{ github.token }}

# Trigger when
on:
  # Push occurs in the main branch
  push:
    branches:
      - main

  # Pull request occurs in the main branch
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          args: --display-style=quiet .
          version: 0.25.0
          token: ${{ github.token }}
  
  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3.0.0
        with:
          version: latest
          args: --check .
          token: ${{ github.token }}
